export { default as StyledText } from './Text';
export { default as StyledButton } from './Button';
export { default as StyledView } from './View';
export { default as StyledImage } from './Image';
export { default as StyledTitleText } from './HeaderTitleText';
export { default as PendingView } from './PendingView';
export { default as StyledInput } from './Input';
export { default as StyledLabel } from './Label';
export { default as FPImage } from './FingerPrintImg';
